os: linux
dist: xenial
before_install:
    - sudo apt-get update -qq
    - sudo apt-get --no-install-recommends install -y cmake cmake-data perl
install:
    - true
perl:
    - "5.26"
python:
    - "3.6"
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
